function generatePDFReport(studentData, results, score, total) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  const primaryColor = [26, 82, 118];
  const accentColor = [39, 174, 96];

  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Learn Italian with Iqra', 105, 18, { align: 'center' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Student Assessment Report', 105, 28, { align: 'center' });

  doc.setFillColor(...accentColor);
  doc.rect(0, 40, 210, 1, 'F');

  let y = 55;

  doc.setTextColor(44, 62, 80);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');

  const fields = [
    ['Student Name:', studentData.name],
    ['Phone:', studentData.phone],
    ['Course Level:', studentData.level],
    ['Date:', new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })],
    ['Questions:', `${total}`],
    ['Score:', `${score} / ${total} (${Math.round(score/total*100)}%)`]
  ];

  fields.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 70, y);
    y += 8;
  });

  y += 5;
  doc.setFillColor(230, 236, 245);
  doc.rect(15, y - 5, 180, 10, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('Question', 20, y + 2);
  doc.text('Result', 170, y + 2);
  y += 12;

  doc.setFontSize(9);
  results.forEach((r, i) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.text(`${i + 1}.`, 20, y);

    doc.setFont('helvetica', 'normal');
    const questionLines = doc.splitTextToSize(r.question, 120);
    doc.text(questionLines, 28, y);

    if (r.result === 'correct') {
      doc.setTextColor(...accentColor);
      doc.text('CORRECT', 170, y);
    } else {
      doc.setTextColor(231, 76, 60);
      doc.text('WRONG', 170, y);
    }

    doc.setTextColor(44, 62, 80);

    if (r.result === 'wrong') {
      y += 5 + (questionLines.length - 1) * 4.5;
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(8);
      doc.setTextColor(127, 140, 141);
      doc.text(`Correct answer: ${r.correctAnswer}`, 28, y);
      doc.setTextColor(44, 62, 80);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
    } else {
      y += (questionLines.length - 1) * 4.5;
    }

    y += 8;
  });

  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(127, 140, 141);
  doc.text('Generated by Learn Italian with Iqra - Quiz Tool', 105, pageHeight - 10, { align: 'center' });

  return doc;
}
